set_property IOSTANDARD LVCMOS33 [get_ports btn]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[1]}]
set_property PACKAGE_PIN W7 [get_ports {LED[6]}]
set_property PACKAGE_PIN W6 [get_ports {LED[5]}]
set_property PACKAGE_PIN U8 [get_ports {LED[4]}]
set_property PACKAGE_PIN V8 [get_ports {LED[3]}]
set_property PACKAGE_PIN U5 [get_ports {LED[2]}]
set_property PACKAGE_PIN V5 [get_ports {LED[1]}]
set_property PACKAGE_PIN U7 [get_ports {LED[0]}]
set_property PACKAGE_PIN U18 [get_ports btn]
set_property PACKAGE_PIN W5 [get_ports clk]

set_property PACKAGE_PIN W4 [get_ports {an[3]}]
set_property PACKAGE_PIN V4 [get_ports {an[2]}]
set_property PACKAGE_PIN U4 [get_ports {an[1]}]
set_property PACKAGE_PIN U2 [get_ports {an[0]}]

set_property PACKAGE_PIN U17 [get_ports btn1]
set_property PACKAGE_PIN U18 [get_ports btn2]
set_property PACKAGE_PIN T18 [get_ports btn3]
set_property IOSTANDARD LVCMOS33 [get_ports btn1]
set_property IOSTANDARD LVCMOS33 [get_ports btn2]
set_property IOSTANDARD LVCMOS33 [get_ports btn3]

set_property PACKAGE_PIN W19 [get_ports LS]
set_property IOSTANDARD LVCMOS33 [get_ports LS]

set_property PACKAGE_PIN P18 [get_ports Pin1]
set_property PACKAGE_PIN N17 [get_ports Pin2]
set_property PACKAGE_PIN M18 [get_ports Pin3]
set_property PACKAGE_PIN K17 [get_ports Pin4]
set_property IOSTANDARD LVCMOS33 [get_ports Pin3]
set_property IOSTANDARD LVCMOS33 [get_ports Pin1]
set_property IOSTANDARD LVCMOS33 [get_ports Pin2]
set_property IOSTANDARD LVCMOS33 [get_ports Pin4]
set_property SLEW SLOW [get_ports Pin2]
set_property DRIVE 12 [get_ports Pin2]

set_property IOSTANDARD LVCMOS33 [get_ports DS]

set_property PACKAGE_PIN U16 [get_ports Outt]
set_property IOSTANDARD LVCMOS33 [get_ports Outt]

set_property PACKAGE_PIN A15 [get_ports DS]
